// BACKEND BEST PRACTICE: Use environment variables for API URL, fallback to localhost
export const API_BASE_URL = import.meta.env.VITE_API_URL || "/api";

export const TRANSLATIONS = {
    en: {
        home: "Home", farmers: "Farmers", marketplace: "Marketplace", about: "About", myActivity: "My Activity", dashboard: "Dashboard",
        login: "Login", register: "Register", logout: "Logout", quickLinks: "Quick Links", contact: "Contact", privacyPolicy: "Privacy Policy",
        termsOfService: "Terms of Service", rightsReserved: "All rights reserved.", footerDesc: "A B.Tech Final Year Project connecting farmers directly with communities. We build technology that cultivates trust and freshness.",
        heroTitle: "Fresh from Farm to Table", heroSubtitle: "Revolutionizing the supply chain. Connecting conscious consumers with local farmers for a sustainable, healthy future.",
        getStarted: "Get Started", learnMore: "Learn More", goToDashboard: "Go to Dashboard", forFarmers: "For Farmers", forFarmersDesc: "List products, manage inventory, and connect directly with buyers. No middlemen.",
        forCustomers: "For Customers", forCustomersDesc: "Find the freshest produce nearby. Buy directly from the source with transparency.", hyperLocal: "Hyper-Local", hyperLocalDesc: "Smart location matching ensures the lowest food miles and maximum freshness.",
        createAccount: "Create Account", fullName: "Full Name", email: "Email", password: "Password", registerAs: "Register As", farmer: "Farmer", customer: "Customer", admin: "Admin",
        welcomeBack: "Welcome back", authFailed: "Authentication failed", farmerDashboard: "Farmer Dashboard", adminDashboard: "Admin Dashboard", manageInventory: "Manage inventory & track impact.",
        addProduct: "Add Product", listNewProduct: "List New Product", updateProduct: "Update Product", editProduct: "Edit Product", productName: "Product Name",
        priceKg: "Price (₹/kg)", stockKg: "Stock (kg)", category: "Category", locationTag: "Location Tag", visibleNearby: "Visible to nearby customers first.",
        activeProducts: "Active Products", totalRevenue: "Weekly Revenue", comingSoon: "Coming Soon", customers: "Customers", lowStock: "Low Stock",
        myStock: "My Stock", listedProducts: "Listed Products", noProducts: "You haven't listed any products yet.", listFirstProduct: "List First Product",
        edit: "Edit", delete: "Delete", confirmDeleteTitle: "Confirm Deletion", confirmDelete: "Are you sure you want to delete this product? This action cannot be undone.", cancel: "Cancel",
        productDeleted: "Product deleted successfully", productUpdated: "Product updated successfully", searchProduce: "Search produce...", searchFarmer: "Search farmer...",
        region: "Region", all: "All", addToCart: "Add to Cart", yourCart: "Your Cart", cartEmpty: "Cart is empty", startAdding: "Start adding fresh items!",
        browseProducts: "Browse Products", total: "Total", checkout: "Checkout", confirmPay: "Confirm & Pay", processingPayment: "Processing payment...",
        enterAddress: "Enter delivery address", orderPlaced: "Order placed successfully!", orderHistory: "Order History", noOrders: "No Orders Yet",
        startShopping: "Start Shopping", paidVia: "Paid via", verifiedFarmer: "Verified Farmer", rating: "Rating", expert: "Expert", availableProducts: "Available Products",
        contactFarmer: "Contact Farmer", contactDetails: "Contact Details", contactSent: "Contact request sent to", close: "Close", farmersOnboarded: "Farmers Onboarded",
        happyCustomers: "Happy Customers", co2Saved: "CO2 Saved", missionTitle: "Feeding the Future.", missionText: "Welcome to FarmLink, a platform dedicated to transforming the agricultural supply chain. We believe that farmers deserve fair prices for their hard work, and customers deserve fresh, chemical-free produce.",
        myProfile: "My Profile", personalDetails: "Personal Details", joined: "Joined", status: "Status", active: "Active", editProfile: "Edit Profile", changePassword: "Change Password",
        address: "Address", phone: "Phone", productImage: "Product Image", uploadImage: "Upload Image", imagePreview: "Image Preview",
        selectCategory: "Select Category", selectLocation: "Select Location", saveChanges: "Save Changes", currentPassword: "Current Password",
        newPassword: "New Password", confirmPassword: "Confirm New Password", passwordChanged: "Password changed successfully", profileUpdated: "Profile updated successfully",
        specialization: "Specialization", bio: "Bio / Description", wishlist: "Wishlist", addedToWishlist: "Added to wishlist", removedFromWishlist: "Removed from wishlist",
        wishlistEmpty: "Your wishlist is empty", saveForLater: "Save items you want to buy later!", orders: "Orders", myOrders: "My Orders",
        similarProducts: "Similar Products", description: "Description", farmerDetails: "Farmer Details", viewProducts: "View Products", back: "Back",
        productDescPlaceholder: "Enter product details (quality, harvest date, etc.)", cart: "Cart",
        locateMe: "Locate Me", detecting: "Detecting...", locationFound: "Location found: ", locationError: "Could not get location",
        forgotPassword: "Forgot Password?", resetPassword: "Reset Password", sendResetLink: "Send Reset Link", backToLogin: "Back to Login", continueWithGoogle: "Continue with Google", continueWithFacebook: "Continue with Facebook", resetLinkSent: "Password reset link sent!", orContinueWith: "Or continue with",
        sortBy: "Sort By", priceLowHigh: "Price: Low to High", priceHighLow: "Price: High to Low", allCategories: "All Categories", trackingPlaced: "Placed", trackingProcessing: "Processing", trackingShipped: "Shipped", trackingDelivered: "Delivered", paymentMethod: "Payment Method",
        leaveReview: "Leave Review", submitReview: "Submit Review", reviewSuccess: "Thank you for your feedback!", passwordTooShort: "Password must be at least 6 characters.", processingBank: "Authenticating with Bank...",
        aiPriceSuggest: "Auto-suggest Price (AI)", aiScanning: "AI Analyzing Crop...", cropScanner: "Crop Disease Scanner", typeMessage: "Type a message...",
        totalUsers: "Total Users", manageUsers: "Manage Users", manageProducts: "Manage Products", platformStats: "Platform Stats", suspendUser: "Suspend User", removeProduct: "Remove Product", systemHealth: "System Health",
        verification: "Verification", getVerified: "Get Verified", uploadDocs: "Upload Verification Docs", docAadhar: "Aadhar Card", docPan: "PAN Card", docPassbook: "Bank Passbook",
        submitVerification: "Submit for Verification", verificationPending: "Verification Pending", reviewDocs: "Review Docs", approve: "Approve", reject: "Reject"
    },
    hi: {
        home: "होम", farmers: "किसान", marketplace: "बाज़ार", about: "हमारे बारे में", myActivity: "मेरी गतिविधि", dashboard: "डैशबोर्ड",
        login: "लॉग इन", register: "रजिस्टर", logout: "लॉग आउट", quickLinks: "त्वरित लिंक", contact: "संपर्क करें", privacyPolicy: "गोपनीयता नीति",
        termsOfService: "सेवा की शर्तें", rightsReserved: "सर्वाधिकार सुरक्षित।", footerDesc: "किसानों को सीधे समुदायों से जोड़ने वाली एक बी.टेक अंतिम वर्ष की परियोजना। हम ऐसी तकनीक बनाते हैं जो विश्वास और ताजगी पैदा करती है।",
        heroTitle: "खेत से सीधे आपकी मेज तक", heroSubtitle: "आपूर्ति श्रृंखला में क्रांति। एक स्थायी, स्वस्थ भविष्य के लिए जागरूक उपभोक्ताओं को स्थानीय किसानों से जोड़ना।",
        getStarted: "शुरू करें", learnMore: "और जानें", goToDashboard: "डैशबोर्ड पर जाएं", forFarmers: "किसानों के लिए", forFarmersDesc: "उत्पाद सूचीबद्ध करें, इन्वेंट्री प्रबंधित करें, और सीधे खरीदारों से जुड़ें। कोई बिचौलिया नहीं।",
        forCustomers: "ग्राहकों के लिए", forCustomersDesc: "आस-पास की सबसे ताज़ा उपज खोजें। सीधे स्रोत से पारदर्शिता के साथ खरीदें।", hyperLocal: "हाइपर-लोकल", hyperLocalDesc: "स्मार्ट लोकेशन मैचिंग सबसे कम फूड माइल्स और अधिकतम ताजगी सुनिश्चित करता है।",
        createAccount: "खाता बनाएं", fullName: "पूरा नाम", email: "ईमेल", password: "पासवर्ड", registerAs: "इस रूप में रजिस्टर करें",
        farmer: "किसान", customer: "ग्राहक", admin: "एडमिन", welcomeBack: "वापसी पर स्वागत है", authFailed: "प्रमाणीकरण विफल", farmerDashboard: "किसान डैशबोर्ड", adminDashboard: "एडमिन डैशबोर्ड",
        manageInventory: "इन्वेंट्री प्रबंधित करें और प्रभाव ट्रैक करें।", addProduct: "उत्पाद जोड़ें", listNewProduct: "नया उत्पाद सूचीबद्ध करें",
        updateProduct: "उत्पाद अपडेट करें", editProduct: "उत्पाद संपादित करें", productName: "उत्पाद का नाम", priceKg: "कीमत (₹/किलो)",
        stockKg: "स्टॉक (किलो)", category: "श्रेणी", locationTag: "स्थान टैग", visibleNearby: "पास के ग्राहकों को पहले दिखाई देगा।",
        activeProducts: "सक्रिय उत्पाद", totalRevenue: "साप्ताहिक राजस्व", comingSoon: "जल्द आ रहा है", customers: "ग्राहक", lowStock: "कम स्टॉक",
        myStock: "मेरा स्टॉक", listedProducts: "सूचीबद्ध उत्पाद", noProducts: "आपने अभी तक कोई उत्पाद सूचीबद्ध नहीं किया है।", listFirstProduct: "पहला उत्पाद सूचीबद्ध करें",
        edit: "संपादित करें", delete: "हटाएं", confirmDeleteTitle: "हटाने की पुष्टि करें", confirmDelete: "क्या आप वाकई इस उत्पाद को हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।",
        cancel: "रद्द करें", productDeleted: "उत्पाद सफलतापूर्वक हटा दिया गया", productUpdated: "उत्पाद सफलतापूर्वक अपडेट किया गया",
        searchProduce: "उपज खोजें...", searchFarmer: "किसान खोजें...", region: "क्षेत्र", all: "सभी", addToCart: "कार्ट में जोड़ा गया",
        yourCart: "आपकी कार्ट", cartEmpty: "कार्ट खाली है", startAdding: "ताज़ा आइटम जोड़ना शुरू करें!", browseProducts: "उत्पाद ब्राउज़ करें",
        total: "कुल", checkout: "चेकआउट", confirmPay: "पुष्टि करें और भुगतान करें", processingPayment: "भुगतान संसाधित हो रहा है...",
        enterAddress: "डिलीवरी पता दर्ज करें", orderPlaced: "ऑर्डर सफलतापूर्वक दिया गया!", orderHistory: "ऑर्डर इतिहास", noOrders: "अभी तक कोई ऑर्डर नहीं",
        startShopping: "खरीदारी शुरू करें", paidVia: "के माध्यम से भुगतान किया गया", verifiedFarmer: "सत्यापित किसान", rating: "रेटिंग",
        expert: "विशेषज्ञ", availableProducts: "उपलब्ध उत्पाद", contactFarmer: "किसान से संपर्क करें", contactDetails: "संपर्क विवरण",
        contactSent: "संपर्क अनुरोध भेजा गया", close: "बंद करें", farmersOnboarded: "किसान जुड़े", happyCustomers: "खुश ग्राहक",
        co2Saved: "CO2 बचाया", missionTitle: "भविष्य को पोषण।", missionText: "FarmLink में आपका स्वागत है, जो कृषि आपूर्ति श्रृंखला को बदलने के लिए समर्पित एक मंच है। हमारा मानना है कि किसानों को उनकी कड़ी मेहनत के लिए उचित मूल्य मिलना चाहिए, और ग्राहकों को ताजी, रसायन मुक्त उपज मिलनी चाहिए।",
        myProfile: "मेरी प्रोफ़ाइल", personalDetails: "व्यक्तिगत विवरण", joined: "शामिल हुए", status: "स्थिति", active: "सक्रिय",
        editProfile: "प्रोफ़ाइल संपादित करें", changePassword: "पासवर्ड बदलें", address: "पता", phone: "फ़ोन", productImage: "उत्पाद छवि",
        uploadImage: "छवि अपलोड करें", imagePreview: "छवि पूर्वावलोकन", selectCategory: "श्रेणी चुनें", selectLocation: "स्थान चुनें",
        saveChanges: "परिवर्तन सहेजें", currentPassword: "वर्तमान पासवर्ड", newPassword: "नया पासवर्ड", confirmPassword: "नए पासवर्ड की पुष्टि करें",
        passwordChanged: "पासवर्ड सफलतापूर्वक बदला गया", profileUpdated: "प्रोफ़ाइल अपडेट की गई", specialization: "विशेषज्ञता (जैसे सब्जियां)", bio: "परिचय / विवरण",
        wishlist: "विशलिस्ट", addedToWishlist: "विशलिस्ट में जोड़ा गया", removedFromWishlist: "विशलिस्ट से हटाया गया", wishlistEmpty: "आपकी विशलिस्ट खाली है", saveForLater: "बाद में खरीदने के लिए आइटम सहेजें!", orders: "आदेश", myOrders: "मेरे आदेश",
        similarProducts: "समान उत्पाद", description: "विवरण", farmerDetails: "किसान विवरण", viewProducts: "उत्पाद देखें", back: "वापस",
        productDescPlaceholder: "उत्पाद विवरण दर्ज करें (गुणवत्ता, फसल तिथि, आदि)", cart: "कार्ट",
        locateMe: "मेरा स्थान खोजें", detecting: "पता लगा रहे हैं...", locationFound: "स्थान मिला: ", locationError: "स्थान प्राप्त नहीं हो सका",
        forgotPassword: "पासवर्ड भूल गए?", resetPassword: "पासवर्ड रीसेट करें", sendResetLink: "रीसेट लिंक भेजें", backToLogin: "लॉगिन पर वापस जाएं", continueWithGoogle: "Google के साथ जारी रखें", continueWithFacebook: "Facebook के साथ जारी रखें", resetLinkSent: "पासवर्ड रीसेट लिंक भेज दिया गया है!", orContinueWith: "या इसके साथ जारी रखें",
        sortBy: "क्रमबद्ध करें", priceLowHigh: "कीमत: कम से ज्यादा", priceHighLow: "कीमत: ज्यादा से कम", allCategories: "सभी श्रेणियां", trackingPlaced: "ऑर्डर दिया", trackingProcessing: "प्रक्रिया में", trackingShipped: "भेज दिया गया", trackingDelivered: "पहुंचा दिया", paymentMethod: "भुगतान विधि",
        leaveReview: "समीक्षा दें", submitReview: "समीक्षा जमा करें", reviewSuccess: "आपकी प्रतिक्रिया के लिए धन्यवाद!", passwordTooShort: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।", processingBank: "बैंक के साथ प्रमाणित कर रहा है...",
        aiPriceSuggest: "AI द्वारा मूल्य सुझाव", aiScanning: "AI विश्लेषण कर रहा है...", cropScanner: "फसल रोग स्कैनर", typeMessage: "संदेश लिखें...",
        totalUsers: "कुल उपयोगकर्ता", manageUsers: "उपयोगकर्ता प्रबंधित करें", manageProducts: "उत्पाद प्रबंधित करें", platformStats: "प्लेटफ़ॉर्म आँकड़े", suspendUser: "उपयोगकर्ता को निलंबित करें", removeProduct: "उत्पाद निकालें", systemHealth: "सिस्टम स्वास्थ्य",
        verification: "सत्यापन", getVerified: "सत्यापित हों", uploadDocs: "दस्तावेज़ अपलोड करें", docAadhar: "आधार कार्ड", docPan: "पैन कार्ड", docPassbook: "बैंक पासबुक",
        submitVerification: "सत्यापनासाठी पाठवा", verificationPending: "सत्यापन लंबित", reviewDocs: "दस्तावेज़ देखें", approve: "स्वीकृत करें", reject: "अस्वीकार करें"
    },
    mr: {
        home: "मुख्य पृष्ठ", farmers: "शेतकरी", marketplace: "बाजारपेठ", about: "आमच्याबद्दल", myActivity: "माझे व्यवहार", dashboard: "डॅशबोर्ड",
        login: "लॉगिन करा", register: "नोंदणी करा", logout: "बाहेर पडा", quickLinks: "महत्वाचे दुवे", contact: "संपर्क", privacyPolicy: "गोपनीयता धोरण",
        termsOfService: "सेवा अटी", rightsReserved: "सर्व हक्क राखीव.", footerDesc: "शेतकऱ्यांना थेट ग्राहकांशी जोडणारा एक नाविन्यपूर्ण प्रकल्प. आम्ही विश्वास आणि ताजेपणा जपतो.",
        heroTitle: "शेत थेट तुमच्या ताटात", heroSubtitle: "पुरवठा साखळीत क्रांती. निरोगी भविष्यासाठी जागरूक ग्राहकांना स्थानिक शेतकऱ्यांशी जोडत आहोत.",
        getStarted: "सुरू करा", learnMore: "अधिक माहिती", goToDashboard: "डॅशबोर्डवर जा", forFarmers: "शेतकऱ्यांसाठी", forFarmersDesc: "उत्पादनांची यादी करा, साठा सांभाळा आणि थेट ग्राहकांशी जोडा. कोणताही मध्यस्थ नाही.",
        forCustomers: "ग्राहकोंसाठी", forCustomersDesc: "जवळपासची ताजी उत्पादने शोधा. थेट शेतकऱ्यांकडून पारदर्शकतेने खरेदी करा.", hyperLocal: "अगदी जवळचे", hyperLocalDesc: "स्मार्ट लोकेशन यंत्रणेमुळे कमीत कमी प्रवास आणि जास्तीत जास्त ताजेपणा.",
        createAccount: "खाते तयार करा", fullName: "पूर्ण नाव", email: "ईमेल", password: "पासवर्ड", registerAs: "नोंदणीचा प्रकार",
        farmer: "शेतकरी", customer: "ग्राहक", admin: "प्रशासक", welcomeBack: "स्वागत आहे", authFailed: "लॉगिन अयशस्वी", farmerDashboard: "शेतकरी डॅशबोर्ड", adminDashboard: "प्रशासक डॅशबोर्ड",
        manageInventory: "साठा आणि विक्रीचे व्यवस्थापन करा.", addProduct: "उत्पादन जोडा", listNewProduct: "नवीन उत्पादन नोंदवा",
        updateProduct: "माहिती अद्ययावत करा", editProduct: "उत्पादन संपादित करा", productName: "उत्पादनाचे नाव", priceKg: "किंमत (₹/कि.ग्रॅ.)",
        stockKg: "साठा (कि.ग्रॅ.)", category: "वर्गवारी", locationTag: "गावाचे नाव", visibleNearby: "जवळपासच्या ग्राहकांना आधी दिसेल.",
        activeProducts: "सक्रिय उत्पादने", totalRevenue: "साप्ताहिक कमाई", comingSoon: "लवकरच येत आहे", customers: "ग्राहक", lowStock: "कमी साठा",
        myStock: "माझा साठा", listedProducts: "नोंदवलेली उत्पादने", noProducts: "तुम्ही अद्याप कोणतीही उत्पादने नोंदवली नाहीत.",
        listFirstProduct: "पहिले उत्पादन नोंदवा", edit: "संपादित करा", delete: "काढून टाका", confirmDeleteTitle: "खात्री करा",
        confirmDelete: "तुम्हाला हे उत्पादन नक्की काढून टाकायचे आहे का? ही कृती परत घेता येणार नाही.", cancel: "रद्द करा", productDeleted: "उत्पादन यशस्वीरित्या काढले",
        productUpdated: "माहिती यशस्वीरित्या बदलली", searchProduce: "भाजीपाला/फळे शोधा...", searchFarmer: "शेतकरी शोधा...", region: "विभाग",
        all: "सर्व", addToCart: "कार्टमध्ये टाका", yourCart: "तुमची पिशवी (कार्ट)", cartEmpty: "कार्ट रिकामी आहे", startAdding: "ताजी उत्पादने खरेदी करा!",
        browseProducts: "उत्पादने पहा", total: "एकूण", checkout: "पैसे भरा", confirmPay: "नक्की करा आणि पैसे द्या",
        processingPayment: "पेमेंट होत आहे...", enterAddress: "पत्ता टाका", orderPlaced: "ऑर्डर यशस्वी झाली!",
        orderHistory: "जुन्या ऑर्डर्स", noOrders: "अद्याप ऑर्डर्स नाहीत", startShopping: "खरेदी सुरू करा", paidVia: "याद्वारे पैसे दिले:",
        verifiedFarmer: "प्रमाणित शेतकरी", rating: "दर्जा", expert: "तज्ञ", availableProducts: "उपलब्ध उत्पादने", contactFarmer: "शेतकऱ्याशी संपर्क साधा",
        contactDetails: "संपर्क माहिती", contactSent: "संपर्क विनंती पाठवली", close: "बंद करा", farmersOnboarded: "शेतकरी जोडले",
        happyCustomers: "समाधानी ग्राहक", co2Saved: "CO2 वाचवला", missionTitle: "भविष्याचे पोषण", missionText: "FarmLink मध्ये स्वागत आहे. कृषी क्षेत्रातील पुरवठा साखळी सुधारण्यासाठी आम्ही कटिबद्ध आहोत. शेतकऱ्यांना कष्टाचा योग्य मोबदला आणि ग्राहकांना विषमुक्त अन्न मिळावे, हेच आमचे ध्येय आहे.",
        myProfile: "माझे प्रोफाइल", personalDetails: "वैयक्तिक माहिती", joined: "कधी जोडले", status: "स्थिती", active: "सक्रिय",
        editProfile: "प्रोफाइल बदला", changePassword: "पासवर्ड बदला", address: "पत्ता", phone: "मोबाईल", productImage: "उत्पादनाचा फोटो",
        uploadImage: "फोटो जोडा", imagePreview: "फोटो प्रिव्ह्यू", selectCategory: "वर्गवारी निवडा", selectLocation: "ठिकाण निवडा",
        saveChanges: "बदल साठवा", currentPassword: "जुना पासवर्ड", newPassword: "नवीन पासवर्ड", confirmPassword: "नवीन पासवर्ड (पुन्हा)",
        passwordChanged: "पासवर्ड यशस्वीरित्या बदलला", profileUpdated: "प्रोफाइल माहिती बदलली", specialization: "विशेषता (पिके)", bio: "परिचय / माहिती",
        wishlist: "पसंतीची यादी", addedToWishlist: "पसंतीमध्ये जोडले", removedFromWishlist: "पसंतीतून काढले", wishlistEmpty: "तुमची पसंतीची यादी रिकामी आहे", saveForLater: "नंतर खरेदी करण्यासाठी साठवा!", orders: "ऑर्डर्स", myOrders: "माझ्या ऑर्डर्स",
        similarProducts: "यासारखी इतर उत्पादने", description: "सविस्तर माहिती", farmerDetails: "शेतकऱ्याची माहिती", viewProducts: "उत्पादने पहा", back: "मागे",
        productDescPlaceholder: "उत्पादनाबद्दल माहिती द्या (दर्जा, काढणी तारीख इ.)", cart: "कार्ट",
        locateMe: "माझे ठिकाण शोधा", detecting: "शोधत  आहे...", locationFound: "ठिकाण सापडले: ", locationError: "ठिकाण मिळू शकले नाही",
        forgotPassword: "पासवर्ड विसरलात?", resetPassword: "पासवर्ड रीसेट करा", sendResetLink: "रीसेट लिंक पाठवा", backToLogin: "लॉगिनवर परत जा", continueWithGoogle: "Google सह सुरू ठेवा", continueWithFacebook: "Facebook सह सुरू ठेवा", resetLinkSent: "पासवर्ड रीसेट लिंक पाठवली आहे!", orContinueWith: "किंवा याद्वारे सुरू ठेवा",
        sortBy: "क्रमवारी", priceLowHigh: "किंमत: कमी ते जास्त", priceHighLow: "किंमत: जास्त ते कमी", allCategories: "सर्व श्रेणी", trackingPlaced: "ऑर्डर दिली", trackingProcessing: "प्रक्रिया सुरू", trackingShipped: "पाठवली", trackingDelivered: "पोहोचवली", paymentMethod: "पेमेंट पद्धत",
        leaveReview: "पुनरावलोकन द्या", submitReview: "पुनरावलोकन पाठवा", reviewSuccess: "तुमच्या अभिप्रायाबद्दल धन्यवाद!", passwordTooShort: "पासवर्ड किमान 6 अक्षरांचा असावा.", processingBank: "बँकेशी प्रमाणित करत आहे...",
        aiPriceSuggest: "AI किंमत सुचवा", aiScanning: "AI विश्लेषण करत आहे...", cropScanner: "पीक रोग स्कॅनर", typeMessage: "संदेश लिहा...",
        totalUsers: "एकूण वापरकर्ते", manageUsers: "वापरकर्ते व्यवस्थापित करा", manageProducts: "उत्पादने व्यवस्थापित करा", platformStats: "प्लॅटफॉर्म आकडेवारी", suspendUser: "वापरकर्ता निलंबित करा", removeProduct: "उत्पादन काढा", systemHealth: "सिस्टम आरोग्य",
        verification: "सत्यापन", getVerified: "सत्यापित व्हा", uploadDocs: "कागदपत्रे अपलोड करा", docAadhar: "आधार कार्ड", docPan: "पॅन कार्ड", docPassbook: "बँक पासबुक",
        submitVerification: "सत्यापनासाठी पाठवा", verificationPending: "सत्यापन प्रलंबित", reviewDocs: "कागदपत्रे तपासा", approve: "मंजूर करा", reject: "नाकारा"
    }
};

export const LOCATIONS = ["Satara", "Mumbai", "Pune", "Nashik", "Nagpur", "Kolhapur", "Aurangabad", "Solapur", "Thane", "Amravati", "Ratnagiri", "Sangli", "Latur", "Dhule", "Akola"];
export const CATEGORIES = ["Vegetables", "Fruits", "Grains", "Dairy"];

export const mockFarmers = [
    { _id: 'f1', name: 'Ramesh Kumar', location: 'Satara', specialization: 'Vegetables', rating: 4.8, phone: '+91 98765 10001', email: 'ramesh.k@farmlink.com', bio: 'Passionate about organic farming for 20 years. Dedicated to sustainable practices.', verified: true, documents: { aadharCard: 'https://images.unsplash.com/photo-1610473210459-4d642e61917f?auto=format&fit=crop&w=400&q=80', panCard: 'https://images.unsplash.com/photo-1610473210459-4d642e61917f?auto=format&fit=crop&w=400&q=80', passbook: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=400&q=80' } },
    { _id: 'f2', name: 'Sita Devi', location: 'Pune', specialization: 'Fruits', rating: 4.9, phone: '+91 98765 10002', email: 'sita.d@farmlink.com', bio: 'Bringing the freshest fruits from Pune valleys directly to your doorstep.', verified: true },
    { _id: 'f3', name: 'Arjun Singh', location: 'Nashik', specialization: 'Grains', rating: 4.5, phone: '+91 98765 10003', email: 'arjun.s@farmlink.com', bio: 'Quality grains from Nashik fields. Pure and unadulterated.', verified: false, verificationStatus: 'Pending', documents: { aadharCard: 'https://images.unsplash.com/photo-1610473210459-4d642e61917f?auto=format&fit=crop&w=400&q=80', panCard: 'https://images.unsplash.com/photo-1610473210459-4d642e61917f?auto=format&fit=crop&w=400&q=80', passbook: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=400&q=80' } },
    { _id: 'f4', name: 'Maria Garcia', location: 'Mumbai', specialization: 'Organic', rating: 4.7, phone: '+91 98765 10004', email: 'maria.g@farmlink.com', bio: 'Urban organic farming specialist focusing on leafy greens.', verified: true },
    { _id: 'f5', name: 'Ahmed Khan', location: 'Nagpur', specialization: 'Dairy', rating: 4.6, phone: '+91 98765 10005', email: 'ahmed.k@farmlink.com', bio: 'Fresh dairy products daily from happy, healthy cattle.', verified: true },
];

export const mockInitialProducts = [
    { _id: 'p1', name: 'Organic Carrots', price: '40', category: 'Vegetables', farmer: 'f1', farmerName: 'Ramesh Kumar', location: 'Satara', stock: 50, image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&q=80&w=400', images: ['https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&q=80&w=800', 'https://www.w3schools.com/html/mov_bbb.mp4', 'https://images.unsplash.com/photo-1582515073490-39981397c445?auto=format&fit=crop&q=80&w=800'], tags: ['Organic'], description: 'Crisp, sweet, and locally grown organic carrots. Harvested fresh every morning.' },
    { _id: 'p2', name: 'Fresh Apples', price: '120', category: 'Fruits', farmer: 'f2', farmerName: 'Sita Devi', location: 'Pune', stock: 30, image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&q=80&w=400', images: ['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&q=80&w=800'], tags: ['Seasonal'], description: 'Juicy and crunchy apples from the orchards of Pune. Perfect for snacks and salads.' },
    { _id: 'p3', name: 'Basmati Rice', price: '90', category: 'Grains', farmer: 'f3', farmerName: 'Arjun Singh', location: 'Nashik', stock: 100, image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=400', images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800', 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&q=80&w=800'], tags: ['Premium'], description: 'Long-grain aromatic Basmati rice. Aged for 2 years. Fluffy and non-sticky.' },
    { _id: 'p4', name: 'Farm Milk', price: '60', category: 'Dairy', farmer: 'f5', farmerName: 'Ahmed Khan', location: 'Nagpur', stock: 20, image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=400', images: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800'], tags: ['Fresh'], description: 'Pure, unadulterated farm-fresh milk. Delivered within hours of milking for maximum nutrition.' },
    { _id: 'p5', name: 'Spinach', price: '30', category: 'Vegetables', farmer: 'f1', farmerName: 'Ramesh Kumar', location: 'Satara', stock: 15, image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=400', images: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=800'], tags: ['Green'], description: 'Tender and nutritious spinach leaves. Grown without harmful pesticides, rich in iron.' },
];

export const mockReviews = [
    { id: 1, user: "Priya S.", rating: 5, date: "2 days ago", comment: "Absolutely incredibly fresh! The quality is so much better than the supermarket." },
    { id: 2, user: "Rahul M.", rating: 4, date: "1 week ago", comment: "Good quality produce and timely delivery. Will buy again." }
];
